name: Android CI

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8

      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Giving Permission for Accessing Gradle file
      run: chmod +x ./ProjectSpace/gradlew

    - name: Compiling Project using Gradle
      run: ./ProjectSpace/gradlew build

    - name: Building CommsGaze APK artifact
      run: |
       ./ProjectSpace/gradlew assembleDebug  -b ProjectSpace/opencv/build.gradle
       ./ProjectSpace/gradlew assembleDebug  -b ProjectSpace/commsgaze/build.gradle

    - uses: actions/upload-artifact@v1
      with:
        name: CommsGaze_APK
        path: ./ProjectSpace/commsgaze/build/outputs/apk/debug/commsgaze-debug.apk

    - name: Building Explore APK artifact
      run: |
       ./ProjectSpace/gradlew assembleDebug  -b ProjectSpace/opencv/build.gradle
       ./ProjectSpace/gradlew assembleDebug  -b ProjectSpace/explore/build.gradle

    - uses: actions/upload-artifact@v1
      with:
        name: Explore_APK
        path: ./ProjectSpace/explore/build/outputs/apk/debug/explore-debug.apk
